// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/admin/billing/return": {
    params: {};
  };
  "/api/billing/start": {
    params: {};
  };
  "/api/billing/usage": {
    params: {};
  };
  "/UsageIndicator": {
    params: {};
  };
  "/BillingPlans": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/size-chart": {
    params: {};
  };
  "/app/analytics": {
    params: {};
  };
  "/app/billing": {
    params: {};
  };
  "/app/widget": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/admin/billing/return" | "/api/billing/start" | "/api/billing/usage" | "/UsageIndicator" | "/BillingPlans" | "/auth/login" | "/auth/*" | "/app" | "/app/size-chart" | "/app/analytics" | "/app/billing" | "/app/widget";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/admin.billing.return.jsx": {
    id: "routes/admin.billing.return";
    page: "/admin/billing/return";
  };
  "routes/api.billing.start.jsx": {
    id: "routes/api.billing.start";
    page: "/api/billing/start";
  };
  "routes/api.billing.usage.jsx": {
    id: "routes/api.billing.usage";
    page: "/api/billing/usage";
  };
  "routes/UsageIndicator.jsx": {
    id: "routes/UsageIndicator";
    page: "/UsageIndicator";
  };
  "routes/BillingPlans.jsx": {
    id: "routes/BillingPlans";
    page: "/BillingPlans";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/size-chart" | "/app/analytics" | "/app/billing" | "/app/widget";
  };
  "routes/app.size-chart.jsx": {
    id: "routes/app.size-chart";
    page: "/app/size-chart";
  };
  "routes/app.analytics.jsx": {
    id: "routes/app.analytics";
    page: "/app/analytics";
  };
  "routes/app.billing.jsx": {
    id: "routes/app.billing";
    page: "/app/billing";
  };
  "routes/app.widget.jsx": {
    id: "routes/app.widget";
    page: "/app/widget";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/admin.billing.return": typeof import("./app/routes/admin.billing.return.jsx");
  "routes/api.billing.start": typeof import("./app/routes/api.billing.start.jsx");
  "routes/api.billing.usage": typeof import("./app/routes/api.billing.usage.jsx");
  "routes/UsageIndicator": typeof import("./app/routes/UsageIndicator.jsx");
  "routes/BillingPlans": typeof import("./app/routes/BillingPlans.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.size-chart": typeof import("./app/routes/app.size-chart.jsx");
  "routes/app.analytics": typeof import("./app/routes/app.analytics.jsx");
  "routes/app.billing": typeof import("./app/routes/app.billing.jsx");
  "routes/app.widget": typeof import("./app/routes/app.widget.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
};