-- Analytics de pedidos originados do botão Omafit (_source=omafit_tryon)
create table if not exists public.order_analytics_omafit (
  id bigint generated by default as identity primary key,
  shop_domain text not null,
  order_id text not null,
  order_name text,
  order_number bigint,
  order_created_at timestamptz,
  order_updated_at timestamptz,
  currency text,
  total_price numeric,
  omafit_line_items_count integer not null default 0,
  source text not null default 'omafit_tryon',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists order_analytics_omafit_shop_order_uidx
  on public.order_analytics_omafit (shop_domain, order_id);

create index if not exists order_analytics_omafit_shop_created_idx
  on public.order_analytics_omafit (shop_domain, order_created_at desc);
